### ISSUE TITLE
Client Birthdate validaion error message

### ISSUE THREAD

**Issue by hady44** [SEGUC17/mean_squad#235]
**1. Severity:** Low
**2. Reported by:** Hady Yasser
**3. Description:**
  Using a word as a birth date should produce an error more specific than "Cannot register new client "

**4. Steps to reproduce the issue:**
    Sign up and write "hady" as a birth date 

**5. Expected result:**
An appropriate error message should be displayed

**Comment by ameniawy** [comment]
Provide a screenshot where you can write "hady" in the date field.

**Comment by hady44** [comment]
![hadydate](https://cloud.githubusercontent.com/assets/25092344/25582298/c5ad834c-2e8c-11e7-8dbb-0155135704e9.png)

**Comment by ameniawy** [comment]
1) I can't reproduce your problem, as the field is shown as a "date" field from my side of things. So that could be a problem with your browser.
![image](https://cloud.githubusercontent.com/assets/17433149/25582411/7c1d067a-2e8d-11e7-8845-8a9bea1f25cd.png)

2) The error message needn't be more descriptive, entering wrong data prevented the backend end from adding the form in the database and a message has been shown to the user.
